name: itis
channels: 
    - conda-forge
    - plotly
dependencies:
    - pandas==1.5.3
    - plotly==5.13.1
    - fastparquet==2024.2.0
    - plotly_express=0.4.1
    - streamlit=1.31.1
    - duckdb=0.7.1
    - polars=1.17.1
